---
- name: "Prom Node Exporter | Create directories tree for node_exporter"
  ansible.builtin.file:
    path: "{{ prom_node_exporter_basedir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Prom Node Exporter | Copy docker-compose.yaml template"
  ansible.builtin.template:
    src: "docker-compose.yaml.j2"
    dest: "{{ prom_node_exporter_basedir }}/docker-compose.yaml"
    owner: root
    group: root
    mode: "0640"
  notify: "Restart node_exporter"

- name: "Prom Node Exporter | Start node_exporter"
  ansible.builtin.command:
    cmd: "docker compose -f {{ prom_node_exporter_basedir }}/docker-compose.yaml up -d"
  register: cmd_output
  changed_when: cmd_output.rc != 0
