---
- name: "Restart node_exporter"
  ansible.builtin.command:
    cmd: "docker compose -f {{ prom_node_exporter_basedir }}/docker-compose.yaml up -d --force-recreate"
  register: cmd_output
  changed_when: cmd_output.rc != 0
